run:
  timeout: 1m

linters:
  enable-all: true
  disable:
    - exhaustivestruct # has a lot of false-positive, because default zero value is not bad
    - nlreturn # not good for short functions (https://github.com/ssgreg/nlreturn/issues/6)
    - wsl # strange suggestions for me.

linters-settings:
  lll:
    line-length: 110
  gci:
    local-prefixes: github.com/kulti/task-list-bot
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: (_test\.go)
      linters:
        - gosec # security is not make sense in tests
        - noctx # it's ok to do simple http request without context in tests

    # go:generate lines can be realy long
    - linters:
        - lll
      source: "^//go:generate "
