// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go

// Package processor_test is a generated GoMock package.
package processor_test

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockRepository is a mock of repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateNewSprint mocks base method
func (m *MockRepository) CreateNewSprint(begin, end time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewSprint", begin, end)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewSprint indicates an expected call of CreateNewSprint
func (mr *MockRepositoryMockRecorder) CreateNewSprint(begin, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewSprint", reflect.TypeOf((*MockRepository)(nil).CreateNewSprint), begin, end)
}
